# THIS ANSIBLE PLAYBOOK FOR DEPLOYING AND INSTALLATION OF IRODS
# MAINTAINER Ahmed Abdullah <ahmedaabdulwahed@gmail.com>

- hosts: servers
  become: yes
  vars:
    cloud: yes
  roles:
    - role: common

# Install PostgreSQL
- hosts: masters
  become: yes
  vars:
    cloud: yes
  tasks:
    - include: roles/icat/tasks/postgresql.yml

- hosts: masters
  become: yes
  become_user: postgres
  gather_facts: no
  vars:
    cloud: yes
    ansible_ssh_pipelining: yes
  tasks:
    - include: roles/icat/tasks/db.yml

# Install iCAT
- hosts: masters
  become: yes
  vars:
    cloud: yes
  roles:
    - role: icat

# Install resources
- hosts: slaves
  become: yes
  vars:
    cloud: yes
  roles:
    - role: resources

# Initialize iRODS replica
- hosts: masters
  become: yes
  vars:
    cloud: yes
    ansible_ssh_pipelining: yes
  roles:
    - role: replica

# Setup PAM authentication and Cloud Browser
- hosts: masters
  become: yes
  vars:
    cloud: yes
  roles:
    - role: auth
    - role: cloud-browser
