---

- name: Add keyserver to apt
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

- name: Add custom postgres repo to apt
  lineinfile: dest=/etc/apt/sources.list.d/pgdg.list
              line="deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" state=present
              create=yes

- name: Install PostgreSQL and required packages
  apt: name={{item}} update_cache=yes
  with_items:
     - python-software-properties
     - software-properties-common
     - libpq-dev
     - python-psycopg2
     - postgresql-9.4

- name: PostgreSQL should listen on all ports
  lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf
              regexp="^listen_addresses"
              line="listen_addresses='*'" state=present

- name: PostgreSQL should allow access to host
  copy: src=roles/icat/files/pg_hba.conf  dest=/etc/postgresql/9.4/main/pg_hba.conf

- name: Configure PostgreSQL
  template: src=roles/icat/templates/postgresql.j2 dest=/etc/postgresql/9.4/main/postgresql.conf

- name: Restart PostgreSQL
  service: name=postgresql state=restarted
