# basic defaults
irods_icat: ftp://ftp.renci.org/pub/irods/releases/4.1.8/ubuntu14/irods-icat-4.1.8-ubuntu14-x86_64.deb
irods_postgre: ftp://ftp.renci.org/pub/irods/releases/4.1.8/ubuntu14/irods-database-plugin-postgres-1.8-ubuntu14-x86_64.deb
icat_pkg: irods-icat-4.1.8-ubuntu14-x86_64.deb
postgre_pkg: irods-database-plugin-postgres-1.8-ubuntu14-x86_64.deb
