---

- name: Add Java 8 repo
  apt_repository: repo='ppa:webupd8team/java'

- name: Install Unzip, Apache 2, Java 8 and Tomcat 7
  apt: name={{ item }} force=yes
  with_items:
    - unzip
    - tomcat7 
    - apache2
    - oracle-java8-installer

- name: Remove Tomcat webapps ROOT
  file: path=/var/lib/tomcat7/webapps/ROOT/ state=absent

- name: Configure Tomcat server 
  copy: src=server.xml dest=/etc/tomcat7/server.xml

- name: Copy configuration file
  template: src=irods-cloud-backend-config.groovy.j2 dest=/etc/irods-cloud-backend-config.groovy

- name: Restart Tomcat
  service: name=tomcat7 state=restarted

- name: Download cloud-browser
  command: wget -O /var/lib/tomcat7/webapps/ROOT.war {{ cloud_browser_pkg }}

- name: Download cloud-browser frontend
  command: wget {{ cloud_browser_frontend }}

- name: Unarchive cloud-browser frontend
  command: unzip -o -d /var/www/html irods-cloud-frontend.zip

- name: Configure frontend to the deployed backend container
  lineinfile:
    dest=/var/www/html/irods-cloud-frontend/app/components/globals.js
    regexp="location.hostname"
    line="        var HOST = \"https://{{ dns }}:443/irods-cloud-backend/\";"
    backrefs=yes

- name: Copy AJP Apache conf
  template: src=ajp.apache.j2 dest=/etc/apache2/sites-available/ajp.apache.conf

- name: Enable Apache proxy_ajp and ssl modules
  shell: 
    a2enmod proxy_ajp ssl;
    a2dissite 000-default;
    a2ensite ajp.apache

- name: Start cloud-browser 
  service: name=apache2 state=restarted
