---
- name: Install OpenJDK 7 & Unzip & Apache 2 & Tomcat 7
  apt: name={{ item }} force=yes
  with_items:
    - openjdk-7-jdk
    - unzip
    - tomcat7 
    - apache2

- name: Remove Tomcat webapps ROOT
  file: path=/var/lib/tomcat7/webapps/ROOT/ state=absent

- name: Configure Tomcat server 
  copy: src=server.xml dest=/etc/tomcat7/server.xml

- name: Copy configuration file
  template: src=irods-cloud-backend-config.groovy.j2 dest=/etc/irods-cloud-backend-config.groovy

- name: Restart Tomcat
  service: name=tomcat7 state=restarted

- name: Install cloud-browser
  command: wget -O /var/lib/tomcat7/webapps/ROOT.war {{ cloud_browser_pkg }}

- name: Download cloud-browser frontend
  command: wget {{ cloud_browser_frontend }}

- name: Unzip cloud-browser frontend
  command: unzip -o -d /var/www/html irods-cloud-frontend.zip

- name: Change document root of 000-default site, set ServerName, and set ProxyPassMatch
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp='/var/www/html' line="        DocumentRoot /var/www/html/irods-cloud-frontend\n        ServerName {{ dns }}\n        ProxyPassMatch /irods-cloud-backend/(.*) ajp://localhost:8009/$1"

- name: Configure frontend to the deployed backend container
  shell: sed -i "s/location.hostname+\":8080/\"{{ dns }}\"+\":80/g" /var/www/html/irods-cloud-frontend/app/components/globals.js

#- name: Copy AJP Apache conf
#  template: src=ajp.apache.j2 dest=/etc/apache2/sites-available/ajp.apache.conf

- name: Enable Apache proxy_ajp module
  shell: a2enmod proxy_ajp;

#- name: Set ServerName for Apache
#  shell: echo "ServerName {{ dns }}" | sudo tee /etc/apache2/conf-available/fqdn.conf; sudo a2enconf fqdn

- name: Start cloud-browser 
  service: name=apache2 state=restarted
