---
#- name: Install OpenJDK 7
#  shell: 
#     apt-get -y install openjdk-7-jdk unzip;
#     update-java-alternatives -s java-1.7.0-openjdk-amd64

- name: Create common directories
  shell: 
    mkdir -p /usr/share/tomcat7;
    mkdir -p /usr/share/tomcat7/common;
    mkdir -p /usr/share/tomcat7/common/classes;
    mkdir -p /usr/share/tomcat7/server;
    mkdir -p /usr/share/tomcat7/server/classes;
    mkdir -p /usr/share/tomcat7/shared;
    mkdir -p /usr/share/tomcat7/shared/classes;
    mkdir -p /etc/cloud-browser;

- name: Install OpenJDK 7 & Unzip & Apache 2 & Tomcat 7
  apt: name={{ item }} force=yes
  with_items:
    - openjdk-7-jdk
    - unzip
    - tomcat7 
    - apache2

- name: Update Java alternatives
  command: update-java-alternatives -s java-1.7.0-openjdk-amd64

- name: Remove Tomcat webapps ROOT
  command: rm -rf /var/lib/tomcat7/webapps/ROOT

#- name: Configure Tomcat server 
#  copy: src=server.xml dest=/etc/tomcat7/server.xml

- name: Copy configuration file
  template: src=irods-cloud-backend-config.groovy.j2 dest=/etc/irods-cloud-backend-config.groovy

- name: Install cloud-browser
  get_url: url={{ cloud_browser_pkg }} dest=/var/lib/tomcat7/webapps/irods-cloud-backend.war

#- name: Change cloud-browser root
#  shell: mv /var/lib/tomcat7/webapps/irods-cloud-backend.war /var/lib/tomcat7/webapps/ROOT.war

- name: Download cloud-browser frontend
  get_url: url={{ cloud_browser_frontend }} dest=/var/www/html/irods-cloud-frontend.zip

- name: Unzip cloud-browser frontend
  command: chdir=/var/www/html unzip -u -o irods-cloud-frontend.zip

- name: Configure frontend to the deployed backend container
  shell: ip="$(hostname -i)"; sed -i "s/location.hostname/\"$ip\"/g" /var/www/html/irods-cloud-frontend/app/components/globals.js

#- name: Copy AJP Apache conf
#  template: src=ajp.apache.j2 dest=/etc/apache2/sites-available/ajp.apache

#- name: Reload Apache configuration
#  shell:
#    a2enmod proxy_ajp;
#    a2dissite 000-default;
#    a2ensite ajp.apache;
#    service apache2 reload

#- name: Configure cloud-browser config
#  template: src=cloud-browser-config.j2  dest=/opt/irods/update-cloud-browser-config.sh

#- name: Copy Tomcat start script
#  copy: src=tomcatstart.sh dest=/opt/irods/tcstart.sh

#- name: Reset permissions
#  shell: chmod a+x /opt/irods/*.sh

- name: Start cloud-browser 
  shell:
    service apache2 restart;
#    /opt/irods/update-cloud-browser-config.sh;
#    /opt/irods/tcstart.sh;
