---

- name: Add Java 8 repo
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 license
  shell:
    echo debconf shared/accepted-oracle-license-v1-1 select true | \
    sudo debconf-set-selections;
    echo debconf shared/accepted-oracle-license-v1-1 seen true | \
    sudo debconf-set-selections;

- name: Install Unzip, Apache 2, Java 8, and Tomcat 7
  apt: name={{ item }} force=yes 
  with_items:
    - oracle-java8-installer
    - unzip
    - tomcat7 
    - apache2

- name: Remove Tomcat webapps ROOT folder
  file: path=/var/lib/tomcat7/webapps/ROOT/ state=absent

- name: Configure Tomcat server 
  copy: src=server.xml dest=/etc/tomcat7/server.xml

- name: Copy configuration file
  template: src=irods-cloud-backend-config.groovy.j2 dest=/etc/irods-cloud-backend-config.groovy

- name: Set JAVA_HOME for Tomcat
  lineinfile:
    dest=/etc/default/tomcat7
    regexp="^#JAVA_HOME"
    line="JAVA_HOME=/usr/lib/jvm/java-8-oracle"
    backrefs=yes

- name: Restart Tomcat
  service: name=tomcat7 state=restarted

- name: Download cloud-browser
  command: wget -O /var/lib/tomcat7/webapps/ROOT.war {{ cloud_browser_pkg }}

- name: Download cloud-browser frontend
  command: wget {{ cloud_browser_frontend }}

- name: Unarchive cloud-browser frontend
  command: unzip -o -d /var/www/html irods-cloud-frontend.zip

- name: Configure frontend to the deployed backend container
  lineinfile:
    dest=/var/www/html/irods-cloud-frontend/app/components/globals.js
    regexp="location.hostname"
    line="        var HOST = \"https://{{ dns }}:443/irods-cloud-backend/\";"
    backrefs=yes

- name: Copy AJP Apache conf
  template: src=ajp.apache.j2 dest=/etc/apache2/sites-available/ajp.apache.conf

- name: Enable Apache proxy_ajp and ssl modules
  shell: 
    a2enmod proxy_ajp ssl;
    a2dissite 000-default;
    a2ensite ajp.apache;

- name: Add generated chain.pem to Java cacerts
  command: keytool -import -storepass changeit -noprompt -file /etc/irods/chain.pem -keystore /usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts
  ignore_errors: yes

- name: Start cloud-browser 
  service: name=apache2 state=restarted
