---
- name: Install OpenJDK 7 & Unzip & Apache 2 & Tomcat 7
  apt: name={{ item }} force=yes
  with_items:
    - openjdk-7-jdk
    - unzip
    - tomcat7 
    - apache2

- name: Remove Tomcat webapps ROOT
  command: rm -rf /var/lib/tomcat7/webapps/ROOT*

#- name: Configure Tomcat server 
#  copy: src=server.xml dest=/etc/tomcat7/server.xml

- name: Copy configuration file
  template: src=irods-cloud-backend-config.groovy.j2 dest=/etc/irods-cloud-backend-config.groovy

- name: Install cloud-browser
  get_url: url={{ cloud_browser_pkg }} dest=/var/lib/tomcat7/webapps/ROOT.war

- name: Download cloud-browser frontend
  get_url: url={{ cloud_browser_frontend }} dest=/tmp/irods-cloud-frontend.zip

- name: Unzip cloud-browser frontend
  command: chdir=/tmp unzip -u -o irods-cloud-frontend.zip

- name: Move frontend to Apache root
  shell: mv -n /tmp/irods-cloud-frontend/* /var/www/html/

- name: Configure frontend to the deployed backend container
  shell: sed -i "s/location.hostname+\":8080\/irods-cloud-backend/\"{{ ansible_ssh_host }}\"+\":8080/g" /var/www/html/app/components/globals.js

#- name: Copy AJP Apache conf
#  template: src=ajp.apache.j2 dest=/etc/apache2/sites-available/ajp.apache

#- name: Reload Apache configuration
#  shell:
#    a2enmod proxy_ajp;
#    a2dissite 000-default;
#    a2ensite ajp.apache;
#    service apache2 reload

- name: Set ServerName for Apache
  shell: echo "ServerName {{ dns }}" | sudo tee /etc/apache2/conf-available/fqdn.con; sudo a2enconf fqdn

- name: Start cloud-browser 
  command: service apache2 restart;
