---
- name: Configure replica
  template: src=replica.j2 dest=/opt/irods/replica.sh

- name: Set replica script to be executable by all
  file: path=/opt/irods/replica.sh mode=a+x
    
- name: Install replicas
  shell: /opt/irods/replica.sh
  ignore_errors: yes
  become_user: irods
